# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_Rumble_Current.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(264, 130)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(90, 90, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.e_current = QtWidgets.QLineEdit(Dialog)
        self.e_current.setGeometry(QtCore.QRect(200, 50, 51, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_current.sizePolicy().hasHeightForWidth())
        self.e_current.setSizePolicy(sizePolicy)
        self.e_current.setReadOnly(True)
        self.e_current.setObjectName("e_current")
        self.s_alertCurrent = QtWidgets.QSlider(Dialog)
        self.s_alertCurrent.setGeometry(QtCore.QRect(20, 50, 161, 22))
        self.s_alertCurrent.setProperty("value", 33)
        self.s_alertCurrent.setSliderPosition(33)
        self.s_alertCurrent.setOrientation(QtCore.Qt.Horizontal)
        self.s_alertCurrent.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.s_alertCurrent.setObjectName("s_alertCurrent")
        self.l_high_current = QtWidgets.QLabel(Dialog)
        self.l_high_current.setGeometry(QtCore.QRect(40, 20, 141, 16))
        self.l_high_current.setObjectName("l_high_current")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Setting"))
        self.s_alertCurrent.setToolTip(_translate("Dialog", "Set current at which gamepad rumbles and current shows red."))
        self.l_high_current.setText(_translate("Dialog", "High Current Alert (A)"))
